version: '3'

services:
  app:
    build:
      context: .
    image: contacts-importer/web:latest
    ports:
      - 3000:3000
      - 3035:3035
    volumes:
      - .:/app
    env_file:
      - .env.development
    depends_on:
      - postgres

  postgres:
    image: postgres:9.5
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres